# Generated by Django 2.2.11 on 2020-03-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taquillero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacio')),
            ],
            options={
                'unique_together': {('espacio', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Taquilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('taquillero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquilla.Taquillero')),
            ],
            options={
                'unique_together': {('taquillero', 'row', 'col')},
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Miembro')),
                ('taquilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquilla.Taquilla')),
            ],
        ),
    ]
