# Generated by Django 2.2.11 on 2020-03-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Miembro'),
        ),
        migrations.AddField(
            model_name='voto',
            name='opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Opcion'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Encuesta'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacio'),
        ),
    ]
