# Generated by Django 2.2.11 on 2020-03-05 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('direccion', models.TextField(help_text='Dirección postal completa, puede tener varias líneas')),
                ('telefono', models.CharField(max_length=9)),
                ('avatar', models.ImageField(upload_to=registro.models.upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dato personal',
                'verbose_name_plural': 'datos personales',
            },
        ),
    ]
