# Generated by Django 2.2.11 on 2020-03-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('slug', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('menu', models.CharField(blank=True, help_text='Si quieres que salga en el menú, pon el nombre aqui', max_length=255, null=True)),
                ('body', models.TextField()),
                ('privado', models.BooleanField(default=False)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacio')),
            ],
            options={
                'verbose_name': 'página',
                'ordering': ('espacio', 'orden'),
                'unique_together': {('espacio', 'slug')},
            },
        ),
    ]
