# Generated by Django 2.2.11 on 2020-03-05 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import espacios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('slug', models.CharField(max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=espacios.models.logos_upload_to)),
                ('favicon', models.ImageField(blank=True, help_text='El formato debe ser PNG y tamaño 16x16 o 32x32', null=True, upload_to=espacios.models.favicons_upload_to)),
                ('cuota_minima', models.FloatField(null=True)),
                ('facebook_fanpage', models.URLField(blank=True, null=True)),
                ('facebook_group', models.URLField(blank=True, null=True)),
                ('google_plus', models.URLField(blank=True, null=True)),
                ('google_group', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('www', models.URLField(blank=True, null=True)),
                ('blog', models.URLField(blank=True, null=True)),
                ('google_site', models.URLField(blank=True, null=True)),
                ('cuotas', models.ManyToManyField(related_name='cuenta_de', to='contabilidad.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now=True)),
                ('es_socio', models.BooleanField(default=False)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='espacio',
            name='miembros',
            field=models.ManyToManyField(through='espacios.Miembro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='espacio',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
