# Generated by Django 2.2.11 on 2020-03-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'autorización',
                'verbose_name_plural': 'autorizaciones',
            },
        ),
        migrations.CreateModel(
            name='EntradaSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'entrada y salida',
                'verbose_name_plural': 'entradas y salidas',
                'ordering': ['-entrada'],
            },
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('last_uptime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'lectores',
            },
        ),
    ]
