# Generated by Django 2.2.11 on 2020-03-05 22:08

import adjuntos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoAsiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichero', models.FileField(upload_to=adjuntos.models._upload_to)),
            ],
        ),
    ]
