# Generated by Django 2.2.11 on 2020-03-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('adjuntos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntoasiento',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Asiento'),
        ),
    ]
