# Generated by Django 2.2.11 on 2020-03-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ver_miembros', models.BooleanField(default=True)),
                ('signo', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1)),
            ],
            options={
                'ordering': ('espacio', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
            options={
                'ordering': ('asiento', '-cantidad', '-fecha'),
            },
        ),
    ]
