# Generated by Django 2.2.11 on 2020-03-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='miembro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='espacios.Miembro'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacio'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacio'),
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together={('espacio', 'nombre')},
        ),
    ]
