# Generated by Django 2.2.11 on 2020-03-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('posicion', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'categoría de pago',
                'verbose_name_plural': 'categoríasde de pago',
                'ordering': ('posicion',),
            },
        ),
        migrations.CreateModel(
            name='CuotaPeriodica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'cuota periódica',
                'verbose_name_plural': 'cuotas periódicas',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('porcentaje_comision', models.FloatField(default=0.0)),
                ('comision_fija', models.FloatField(default=0.0)),
                ('liquido', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('posicion', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'forma de pago',
                'verbose_name_plural': 'formas de pago',
                'ordering': ('posicion',),
            },
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cantidad', models.FloatField()),
            ],
            options={
                'verbose_name': 'mensualidad',
                'verbose_name_plural': 'mensualidades',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.FloatField()),
                ('tipo', models.IntegerField(choices=[(1, 'Ingresos'), (2, 'Neutro'), (3, 'Gastos')], default=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuotas.FormaPago')),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
    ]
