# Generated by Django 2.2.11 on 2020-03-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        ('cuotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pagador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='espacios.Miembro'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuotas.CategoriaPago'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Miembro'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuotas.Pago'),
        ),
        migrations.AddField(
            model_name='formapago',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacio'),
        ),
        migrations.AddField(
            model_name='cuotaperiodica',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacio'),
        ),
        migrations.AddField(
            model_name='categoriapago',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacio'),
        ),
    ]
